// src/data/projects.ts
import { Project } from '@/types'

export const projects: Project[] = [
  {
    id: 'ai-assistant',
    title: 'AI-Powered Assistant',
    description: 'Intelligent conversational AI with natural language processing capabilities',
    longDescription: 'Built a sophisticated AI assistant using cutting-edge machine learning models, featuring natural language understanding, context awareness, and multi-turn conversations. Implemented advanced NLP techniques and integrated with various APIs for enhanced functionality.',
    technologies: ['Python', 'TensorFlow', 'OpenAI API', 'FastAPI', 'React'],
    githubUrl: 'https://github.com/VibhorGits/ai-assistant',
    liveUrl: 'https://ai-assistant-demo.com',
    imageUrl: '/images/projects/ai-assistant.jpg',
    featured: true,
    category: 'ai',
    completedAt: '2024-12-01',
  },
  {
    id: 'blockchain-voting',
    title: 'Decentralized Voting System',
    description: 'Secure blockchain-based voting platform with smart contracts',
    longDescription: 'Developed a transparent and secure voting system using blockchain technology. Features include smart contract-based vote counting, voter authentication, real-time results, and complete audit trails. Ensures election integrity through cryptographic security.',
    technologies: ['Solidity', 'Ethereum', 'Web3.js', 'React', 'Node.js'],
    githubUrl: 'https://github.com/VibhorGits/blockchain-voting',
    liveUrl: 'https://secure-vote-platform.com',
    imageUrl: '/images/projects/blockchain-voting.jpg',
    featured: true,
    category: 'blockchain',
    completedAt: '2024-10-15',
  },
  {
    id: 'fullstack-ecommerce',
    title: 'E-Commerce Platform',
    description: 'Full-stack e-commerce solution with modern UI/UX',
    longDescription: 'Comprehensive e-commerce platform featuring user authentication, product catalog, shopping cart, payment integration, order management, and admin dashboard. Built with performance and scalability in mind using modern web technologies.',
    technologies: ['Next.js', 'TypeScript', 'PostgreSQL', 'Stripe', 'Tailwind CSS'],
    githubUrl: 'https://github.com/VibhorGits/ecommerce-platform',
    liveUrl: 'https://modern-ecommerce.com',
    imageUrl: '/images/projects/ecommerce.jpg',
    featured: true,
    category: 'fullstack',
    completedAt: '2024-09-20',
  },
  {
    id: 'mobile-fitness',
    title: 'Fitness Tracking App',
    description: 'Mobile application for fitness tracking and workout planning',
    longDescription: 'Cross-platform mobile app for fitness enthusiasts featuring workout tracking, progress monitoring, social features, and personalized recommendations. Includes integration with wearable devices and health APIs.',
    technologies: ['React Native', 'Firebase', 'Node.js', 'MongoDB', 'Express'],
    githubUrl: 'https://github.com/VibhorGits/fitness-tracker',
    imageUrl: '/images/projects/fitness-app.jpg',
    featured: false,
    category: 'mobile',
    completedAt: '2024-08-10',
  },
  {
    id: 'data-visualization',
    title: 'Data Analytics Dashboard',
    description: 'Interactive dashboard for data visualization and analytics',
    longDescription: 'Professional-grade analytics dashboard with real-time data processing, interactive charts, custom reporting, and export capabilities. Handles large datasets efficiently with optimized queries and caching strategies.',
    technologies: ['D3.js', 'Python', 'Django', 'PostgreSQL', 'Redis'],
    githubUrl: 'https://github.com/VibhorGits/analytics-dashboard',
    liveUrl: 'https://data-insights-dashboard.com',
    imageUrl: '/images/projects/analytics.jpg',
    featured: false,
    category: 'fullstack',
    completedAt: '2024-07-05',
  },
]

export const featuredProjects = projects.filter(project => project.featured)